'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {sample,run}=require('../docs/demo.js');
const good=()=>sample({costResolved:true,differenceResolved:true});
test('initial state has two explicit exceptions',()=>{const r=run(sample());assert.equal(r.status,'DRAFT');assert.equal(r.issueCount,2);});
test('resolving cost alone is insufficient',()=>assert.equal(run(sample({costResolved:true})).issueCount,1));
test('resolving settlement alone is insufficient',()=>assert.equal(run(sample({differenceResolved:true})).issueCount,1));
test('both resolutions produce FINAL',()=>assert.equal(run(good()).status,'FINAL'));
test('missing cost preserves null profit',()=>{const r=run(sample()).rows[3];assert.equal(r.cost,null);assert.equal(r.profit,null);});
test('zero cost is distinct from missing cost',()=>{const s=good();s.manual[3].cost=0;assert.equal(run(s).rows[3].profit,86000);});
test('arithmetic and signed adjustments match fixture',()=>{const r=run(good());assert.deepEqual(r.rows.map(x=>x.profit),[45000,42000,40500,40000]);assert.ok(r.rows.every(x=>x.difference===0));});
test('results are deterministic and inputs unchanged',()=>{const s=sample();const before=JSON.stringify(s);assert.deepEqual(run(s),run(s));assert.equal(JSON.stringify(s),before);});
test('rejects incorrect schema',()=>{const s=good();s.schema='real';assert.throws(()=>run(s),TypeError);});
test('rejects unknown accounting unit',()=>{const s=good();s.unit='USD';assert.throws(()=>run(s),TypeError);});
test('rejects malformed amounts',()=>{for(const v of [NaN,Infinity,1.5,'100',-1,Number.MAX_SAFE_INTEGER+1]){const s=good();s.source[0].sales=v;assert.throws(()=>run(s),TypeError);}});
test('rejects malformed or empty arrays',()=>{for(const s of [null,{}, {...good(),source:[]},{...good(),manual:null}])assert.throws(()=>run(s),TypeError);});
test('rejects duplicate source and manual platforms',()=>{const s=good();s.source.push({...s.source[0]});assert.throws(()=>run(s),TypeError);const t=good();t.manual.push({...t.manual[0]});assert.throws(()=>run(t),TypeError);});
test('rejects unknown source platform',()=>{const s=good();s.source[0].platform='OTHER';assert.throws(()=>run(s),TypeError);});
test('rejects missing manual input',()=>{const s=good();s.manual.pop();assert.throws(()=>run(s),TypeError);});
test('rejects unused manual input',()=>{const s=good();s.source.pop();assert.throws(()=>run(s),TypeError);});
test('rejects non-demo SKU',()=>{const s=good();s.source[0].sku='REAL-CUSTOMER';assert.throws(()=>run(s),TypeError);});
test('rejects undefined cost instead of guessing',()=>{const s=good();delete s.manual[3].cost;assert.throws(()=>run(s),TypeError);});
